accelerate launch train.py \
  --model_name Qwen2.5-Math-7B \
  --model_path /homes/gws/lxh22/models/Qwen2.5-Math-7B \
  --train_data dataset/1shot_rlvr/pi1_r1280.parquet \
  --effective_batch 64 \
  --micro_batch_size 2 \
  --temperature 0.5 \
  --learning_rate 2e-5 \
  --max_steps 400 \
  --log_steps 1 \
  --save_steps 20 \
  --save_root /local1/lxh/save/em \
  --run_name prompted_one_shot_7b_t0.5 \
  --wandb_project one-shot-em 2>&1 | tee em.log